### ISSUE TITLE
ixmp is not compatible with the latest ixmp4 releases

### ISSUE THREAD

**Issue by phackstock** [iiasa/ixmp#642]
ixmp [`main` branch] currently restricts the optional ixmp4 dependency to `>0.15`, this is an issue for the usage in iiasa/scse-update where we need to service both scse-apps and legacy Scenario Explorers.
When used with ixmp4 <0.14, we get the following error:
```python
.venv/lib/python3.11/site-packages/ixmp/_config.py:72: in _platform_default
    ixmp4_databases = ixmp4.conf.settings.storage_directory.joinpath("databases")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E   AttributeError: module 'ixmp4.conf.settings' has no attribute 'storage_directory'
```

**Comment by khaeru** [comment]
Thanks for letting us know about this downstream dependency, which wasn't previously on our radar.

To recap some prior direct discussion with @meksor:
- Until ixmp4 hits v1.0.0, each version/the `main` branch of ixmp will be compatible with only one minor version of ixmp4.
  - For instance, in ixmp v3.11.0, the requirement ([here](https://github.com/iiasa/ixmp/blob/70fbe37544e61a91b193b7649c36fba0a66a947c/pyproject.toml#L63)) was "ixmp4 >= 0.10, < 0.11".
  - Later ([here](https://github.com/iiasa/ixmp/blame/c5b053245e8240c58dfeccd901672d8c5f7f7bb7/pyproject.toml#L62)) it was "ixmp4 >= 0.13, < 0.14".
  - Currently on `main` ([here](https://github.com/iiasa/ixmp/blame/834b82179d422d696d31e016af51e8be4f63a24d/pyproject.toml#L62)) it is "ixmp4 >= 0.14, < 0.15".
    - Thus, it should not be expected to work with ixmp4 < 0.14.
  - With #640 it will advance (on `main` only) to "ixmp4 >= 0.16.3, < 0.17".
    - This will be included in the next release, unless superseded by another PR.
- The general reasons for this:
  - In the 0.y/pre-stable phase, there have been substantial (necessary) changes to the ixmp4 API between minor versions.
  - We lack resources to provide support for more than one minor version at a time.
  - Per iiasa/message_ix#939 (also note the planned release schedule has slipped, again due to lack of resources), we haven't promised such support.
- Once ixmp4 hits v1.0.0, we can work towards offering full (non-beta) support in ixmp/message_ix, which would include broadening compatibility to major releases, e.g. "ixmp4 >= 1.0.0, < 2".

I hope that provides clear enough information for developing code that depends both on ixmp and ixmp4.

To my view the only possible actionable thing here is to maybe copy the above description into the documentation. We could also change the title to "ixmp compatibility with ixmp4 0.16.z" and link it to PR #640 which would then close the issue.
